version: "3"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-local
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgresdb
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/etc/mm/postgresql/data

volumes:
  postgres-data: